"""
Tier 1 built-in exercise map and full Garmin exercise list.

EXERCISE_MAP: fitbod_name -> (garmin_exercise_name, garmin_category)
GARMIN_EXERCISES: list of (name, category) tuples for browser picker / fuzzy match
"""

from __future__ import annotations

# fmt: off
EXERCISE_MAP: dict[str, tuple[str, str]] = {
    # ── Chest ──────────────────────────────────────────────────────────────────
    "Barbell Bench Press": ("BENCH_PRESS", "CHEST"),
    "Dumbbell Bench Press": ("DUMBBELL_BENCH_PRESS", "CHEST"),
    "Incline Barbell Bench Press": ("INCLINE_CHEST_PRESS", "CHEST"),
    "Incline Dumbbell Bench Press": ("INCLINE_DUMBBELL_BENCH_PRESS", "CHEST"),
    "Decline Barbell Bench Press": ("DECLINE_PRESS", "CHEST"),
    "Decline Dumbbell Bench Press": ("DECLINE_DUMBBELL_BENCH_PRESS", "CHEST"),
    "Dumbbell Flyes": ("DUMBBELL_FLYES", "CHEST"),
    "Incline Dumbbell Flyes": ("INCLINE_DUMBBELL_FLYES", "CHEST"),
    "Cable Chest Fly": ("CABLE_CROSSOVER", "CHEST"),
    "Pec Deck": ("PEC_DECK_FLYES", "CHEST"),
    "Machine Chest Press": ("MACHINE_BENCH_PRESS", "CHEST"),
    "Machine Chest Fly": ("PEC_DECK_FLYES", "CHEST"),
    "Push-Up": ("PUSH_UP", "CHEST"),
    "Wide Push-Up": ("WIDE_PUSH_UP", "CHEST"),
    "Diamond Push-Up": ("DIAMOND_PUSH_UP", "CHEST"),
    "Close-Grip Bench Press": ("CLOSE_GRIP_BENCH_PRESS", "CHEST"),
    "Dip": ("DIP", "CHEST"),
    "Weighted Dip": ("WEIGHTED_DIP", "CHEST"),

    # ── Back ───────────────────────────────────────────────────────────────────
    "Barbell Deadlift": ("DEADLIFT", "BACK"),
    "Romanian Deadlift": ("ROMANIAN_DEADLIFT", "BACK"),
    "Sumo Deadlift": ("SUMO_DEADLIFT", "BACK"),
    "Dumbbell Romanian Deadlift": ("DUMBBELL_ROMANIAN_DEADLIFT", "BACK"),
    "Barbell Row": ("BARBELL_ROW", "BACK"),
    "Bent Over Barbell Row": ("BENT_OVER_ROW", "BACK"),
    "Dumbbell Row": ("DUMBBELL_ROW", "BACK"),
    "Seated Cable Row": ("SEATED_CABLE_ROW", "BACK"),
    "Cable Row": ("SEATED_CABLE_ROW", "BACK"),
    "T-Bar Row": ("T_BAR_ROW", "BACK"),
    "Pull-Up": ("PULL_UP", "BACK"),
    "Weighted Pull-Up": ("WEIGHTED_PULL_UP", "BACK"),
    "Chin-Up": ("CHIN_UP", "BACK"),
    "Weighted Chin-Up": ("WEIGHTED_CHIN_UP", "BACK"),
    "Lat Pulldown": ("LAT_PULLDOWN", "BACK"),
    "Wide Grip Lat Pulldown": ("WIDE_GRIP_LAT_PULLDOWN", "BACK"),
    "Close Grip Lat Pulldown": ("CLOSE_GRIP_LAT_PULLDOWN", "BACK"),
    "Machine Row": ("SEATED_ROW_MACHINE", "BACK"),
    "Cable Lat Pulldown": ("LAT_PULLDOWN", "BACK"),
    "Straight Arm Lat Pulldown": ("STRAIGHT_ARM_PULLDOWN", "BACK"),
    "Face Pull": ("FACE_PULL", "BACK"),
    "Hyperextension": ("BACK_EXTENSION", "BACK"),
    "Back Extension": ("BACK_EXTENSION", "BACK"),
    "Good Morning": ("GOOD_MORNING", "BACK"),

    # ── Shoulders ──────────────────────────────────────────────────────────────
    "Barbell Overhead Press": ("OVERHEAD_PRESS", "SHOULDERS"),
    "Seated Barbell Overhead Press": ("SEATED_OVERHEAD_PRESS", "SHOULDERS"),
    "Dumbbell Overhead Press": ("DUMBBELL_OVERHEAD_PRESS", "SHOULDERS"),
    "Seated Dumbbell Overhead Press": ("SEATED_DUMBBELL_OVERHEAD_PRESS", "SHOULDERS"),
    "Arnold Press": ("ARNOLD_PRESS", "SHOULDERS"),
    "Dumbbell Lateral Raise": ("SIDE_LATERAL_RAISE", "SHOULDERS"),
    "Cable Lateral Raise": ("CABLE_SIDE_LATERAL_RAISE", "SHOULDERS"),
    "Dumbbell Front Raise": ("FRONT_RAISE", "SHOULDERS"),
    "Cable Front Raise": ("FRONT_RAISE", "SHOULDERS"),
    "Dumbbell Rear Delt Fly": ("REAR_DELTOID_RAISE", "SHOULDERS"),
    "Cable Rear Delt Fly": ("REAR_DELTOID_RAISE", "SHOULDERS"),
    "Machine Overhead Press": ("SHOULDER_PRESS_MACHINE", "SHOULDERS"),
    "Machine Lateral Raise": ("SIDE_LATERAL_RAISE", "SHOULDERS"),
    "Upright Row": ("UPRIGHT_ROW", "SHOULDERS"),
    "Barbell Upright Row": ("BARBELL_UPRIGHT_ROW", "SHOULDERS"),
    "Shrug": ("DUMBBELL_SHRUG", "SHOULDERS"),
    "Barbell Shrug": ("BARBELL_SHRUG", "SHOULDERS"),
    "Dumbbell Shrug": ("DUMBBELL_SHRUG", "SHOULDERS"),

    # ── Biceps ─────────────────────────────────────────────────────────────────
    "Barbell Curl": ("BARBELL_CURL", "BICEPS"),
    "Dumbbell Curl": ("DUMBBELL_CURL", "BICEPS"),
    "Hammer Curl": ("HAMMER_CURL", "BICEPS"),
    "Incline Dumbbell Curl": ("INCLINE_DUMBBELL_CURL", "BICEPS"),
    "Concentration Curl": ("CONCENTRATION_CURL", "BICEPS"),
    "Cable Curl": ("CABLE_CURL", "BICEPS"),
    "EZ-Bar Curl": ("EZ_BAR_CURL", "BICEPS"),
    "Preacher Curl": ("PREACHER_CURL", "BICEPS"),
    "Machine Curl": ("MACHINE_PREACHER_CURL", "BICEPS"),
    "Seated Dumbbell Curl": ("SEATED_DUMBBELL_CURL", "BICEPS"),
    "Zottman Curl": ("ZOTTMAN_CURL", "BICEPS"),
    "Reverse Curl": ("REVERSE_CURL", "BICEPS"),

    # ── Triceps ────────────────────────────────────────────────────────────────
    "Tricep Pushdown": ("TRICEP_PUSHDOWN", "TRICEPS"),
    "Cable Tricep Pushdown": ("CABLE_TRICEP_PUSHDOWN", "TRICEPS"),
    "Rope Tricep Pushdown": ("ROPE_PUSHDOWN", "TRICEPS"),
    "Overhead Tricep Extension": ("OVERHEAD_TRICEP_EXTENSION", "TRICEPS"),
    "Dumbbell Overhead Tricep Extension": ("DUMBBELL_OVERHEAD_TRICEP_EXTENSION", "TRICEPS"),
    "Cable Overhead Tricep Extension": ("CABLE_OVERHEAD_TRICEP_EXTENSION", "TRICEPS"),
    "Skull Crusher": ("SKULL_CRUSHER", "TRICEPS"),
    "EZ-Bar Skull Crusher": ("SKULL_CRUSHER", "TRICEPS"),
    "Tricep Dip": ("BENCH_DIP", "TRICEPS"),
    "Bench Dip": ("BENCH_DIP", "TRICEPS"),
    "Close Grip Push-Up": ("DIAMOND_PUSH_UP", "TRICEPS"),
    "Machine Tricep Extension": ("TRICEP_EXTENSION_MACHINE", "TRICEPS"),
    "Kickback": ("KICKBACK", "TRICEPS"),
    "Dumbbell Kickback": ("KICKBACK", "TRICEPS"),

    # ── Legs ───────────────────────────────────────────────────────────────────
    "Barbell Squat": ("SQUAT", "LEGS"),
    "Back Squat": ("SQUAT", "LEGS"),
    "Front Squat": ("FRONT_SQUAT", "LEGS"),
    "Goblet Squat": ("GOBLET_SQUAT", "LEGS"),
    "Dumbbell Squat": ("DUMBBELL_SQUAT", "LEGS"),
    "Sumo Squat": ("SUMO_SQUAT", "LEGS"),
    "Bulgarian Split Squat": ("BULGARIAN_SPLIT_SQUAT", "LEGS"),
    "Dumbbell Lunge": ("DUMBBELL_LUNGE", "LEGS"),
    "Barbell Lunge": ("BARBELL_LUNGE", "LEGS"),
    "Walking Lunge": ("WALKING_LUNGE", "LEGS"),
    "Reverse Lunge": ("REVERSE_DUMBBELL_LUNGE", "LEGS"),
    "Leg Press": ("LEG_PRESS", "LEGS"),
    "Hack Squat": ("HACK_SQUAT", "LEGS"),
    "Leg Extension": ("LEG_EXTENSION", "LEGS"),
    "Leg Curl": ("LEG_CURL", "LEGS"),
    "Seated Leg Curl": ("SEATED_LEG_CURL", "LEGS"),
    "Lying Leg Curl": ("LYING_LEG_CURL", "LEGS"),
    "Standing Leg Curl": ("STANDING_LEG_CURL", "LEGS"),
    "Calf Raise": ("CALF_RAISE", "LEGS"),
    "Standing Calf Raise": ("STANDING_CALF_RAISE", "LEGS"),
    "Seated Calf Raise": ("SEATED_CALF_RAISE", "LEGS"),
    "Glute Kickback": ("CABLE_KICKBACK", "LEGS"),
    "Hip Thrust": ("BARBELL_HIP_THRUST", "LEGS"),
    "Barbell Hip Thrust": ("BARBELL_HIP_THRUST", "LEGS"),
    "Dumbbell Hip Thrust": ("DUMBBELL_HIP_THRUST", "LEGS"),
    "Romanian Deadlift (Single Leg)": ("SINGLE_LEG_DEADLIFT", "LEGS"),
    "Single-Leg Romanian Deadlift": ("SINGLE_LEG_DEADLIFT", "LEGS"),
    "Step-Up": ("STEP_UP", "LEGS"),
    "Box Squat": ("BOX_SQUAT", "LEGS"),
    "Smith Machine Squat": ("SMITH_MACHINE_SQUAT", "LEGS"),

    # ── Glutes ─────────────────────────────────────────────────────────────────
    "Cable Pull Through": ("CABLE_PULL_THROUGH", "LEGS"),
    "Kettlebell Swing": ("KETTLEBELL_SWING", "LEGS"),
    "Glute Bridge": ("GLUTE_BRIDGE", "LEGS"),
    "Sumo Deadlift High Pull": ("SUMO_DEADLIFT_HIGH_PULL", "BACK"),

    # ── Core / Abs ─────────────────────────────────────────────────────────────
    "Plank": ("PLANK", "CORE"),
    "Side Plank": ("SIDE_PLANK", "CORE"),
    "Crunch": ("CRUNCH", "CORE"),
    "Sit-Up": ("SIT_UP", "CORE"),
    "Decline Crunch": ("DECLINE_CRUNCH", "CORE"),
    "Bicycle Crunch": ("BICYCLE_CRUNCH", "CORE"),
    "Russian Twist": ("RUSSIAN_TWIST", "CORE"),
    "Leg Raise": ("LEG_RAISE", "CORE"),
    "Hanging Leg Raise": ("HANGING_LEG_RAISE", "CORE"),
    "Hanging Knee Raise": ("HANGING_KNEE_RAISE", "CORE"),
    "Ab Wheel Rollout": ("AB_WHEEL_ROLLOUT", "CORE"),
    "Cable Crunch": ("CABLE_CRUNCH", "CORE"),
    "Woodchopper": ("CABLE_WOOD_CHOP", "CORE"),
    "Cable Woodchopper": ("CABLE_WOOD_CHOP", "CORE"),
    "Dead Bug": ("DEAD_BUG", "CORE"),
    "Hollow Hold": ("HOLLOW_HOLD", "CORE"),
    "V-Up": ("V_UP", "CORE"),
    "Mountain Climber": ("MOUNTAIN_CLIMBER", "CORE"),
    "Flutter Kick": ("FLUTTER_KICK", "CORE"),
    "Pallof Press": ("PALLOF_PRESS", "CORE"),

    # ── Olympic / Power ────────────────────────────────────────────────────────
    "Power Clean": ("POWER_CLEAN", "OLYMPIC"),
    "Hang Power Clean": ("HANG_POWER_CLEAN", "OLYMPIC"),
    "Clean and Jerk": ("CLEAN_AND_JERK", "OLYMPIC"),
    "Snatch": ("SNATCH", "OLYMPIC"),
    "Power Snatch": ("POWER_SNATCH", "OLYMPIC"),
    "Hang Clean": ("HANG_CLEAN", "OLYMPIC"),
    "Push Press": ("PUSH_PRESS", "SHOULDERS"),
    "Push Jerk": ("PUSH_JERK", "SHOULDERS"),

    # ── Cardio / Conditioning ──────────────────────────────────────────────────
    "Burpee": ("BURPEE", "CARDIO"),
    "Box Jump": ("BOX_JUMP", "PLYOMETRICS"),
    "Jumping Jack": ("JUMPING_JACK", "CARDIO"),
    "Jump Rope": ("JUMP_ROPE", "CARDIO"),
    "Battle Ropes": ("BATTLE_ROPES", "CARDIO"),
    "Sled Push": ("SLED_PUSH", "CARDIO"),
    "Farmer's Carry": ("FARMERS_WALK", "CARDIO"),
    "Farmers Walk": ("FARMERS_WALK", "CARDIO"),
}
# fmt: on


# Full Garmin exercise list as (name, category) tuples.
# Used by the browser picker and fuzzy matcher in classifier.py.
GARMIN_EXERCISES: list[tuple[str, str]] = [
    # CHEST
    ("BENCH_PRESS", "CHEST"),
    ("DUMBBELL_BENCH_PRESS", "CHEST"),
    ("INCLINE_CHEST_PRESS", "CHEST"),
    ("INCLINE_DUMBBELL_BENCH_PRESS", "CHEST"),
    ("DECLINE_PRESS", "CHEST"),
    ("DECLINE_DUMBBELL_BENCH_PRESS", "CHEST"),
    ("DUMBBELL_FLYES", "CHEST"),
    ("INCLINE_DUMBBELL_FLYES", "CHEST"),
    ("DECLINE_DUMBBELL_FLYES", "CHEST"),
    ("CABLE_CROSSOVER", "CHEST"),
    ("PEC_DECK_FLYES", "CHEST"),
    ("MACHINE_BENCH_PRESS", "CHEST"),
    ("PUSH_UP", "CHEST"),
    ("WIDE_PUSH_UP", "CHEST"),
    ("DIAMOND_PUSH_UP", "CHEST"),
    ("CLOSE_GRIP_BENCH_PRESS", "CHEST"),
    ("DIP", "CHEST"),
    ("WEIGHTED_DIP", "CHEST"),
    ("CHEST_FLY_MACHINE", "CHEST"),
    ("CHEST_PRESS_MACHINE", "CHEST"),
    ("INCLINE_CABLE_FLY", "CHEST"),
    ("LOW_CABLE_CROSSOVER", "CHEST"),
    # BACK
    ("DEADLIFT", "BACK"),
    ("ROMANIAN_DEADLIFT", "BACK"),
    ("SUMO_DEADLIFT", "BACK"),
    ("DUMBBELL_ROMANIAN_DEADLIFT", "BACK"),
    ("SINGLE_LEG_DEADLIFT", "BACK"),
    ("BARBELL_ROW", "BACK"),
    ("BENT_OVER_ROW", "BACK"),
    ("DUMBBELL_ROW", "BACK"),
    ("SEATED_CABLE_ROW", "BACK"),
    ("T_BAR_ROW", "BACK"),
    ("PULL_UP", "BACK"),
    ("WEIGHTED_PULL_UP", "BACK"),
    ("CHIN_UP", "BACK"),
    ("WEIGHTED_CHIN_UP", "BACK"),
    ("LAT_PULLDOWN", "BACK"),
    ("WIDE_GRIP_LAT_PULLDOWN", "BACK"),
    ("CLOSE_GRIP_LAT_PULLDOWN", "BACK"),
    ("SEATED_ROW_MACHINE", "BACK"),
    ("STRAIGHT_ARM_PULLDOWN", "BACK"),
    ("FACE_PULL", "BACK"),
    ("BACK_EXTENSION", "BACK"),
    ("GOOD_MORNING", "BACK"),
    ("RACK_PULL", "BACK"),
    ("SUMO_DEADLIFT_HIGH_PULL", "BACK"),
    ("INVERTED_ROW", "BACK"),
    ("CABLE_ROW", "BACK"),
    ("NEUTRAL_GRIP_PULLDOWN", "BACK"),
    # SHOULDERS
    ("OVERHEAD_PRESS", "SHOULDERS"),
    ("SEATED_OVERHEAD_PRESS", "SHOULDERS"),
    ("DUMBBELL_OVERHEAD_PRESS", "SHOULDERS"),
    ("SEATED_DUMBBELL_OVERHEAD_PRESS", "SHOULDERS"),
    ("ARNOLD_PRESS", "SHOULDERS"),
    ("SIDE_LATERAL_RAISE", "SHOULDERS"),
    ("CABLE_SIDE_LATERAL_RAISE", "SHOULDERS"),
    ("FRONT_RAISE", "SHOULDERS"),
    ("REAR_DELTOID_RAISE", "SHOULDERS"),
    ("SHOULDER_PRESS_MACHINE", "SHOULDERS"),
    ("UPRIGHT_ROW", "SHOULDERS"),
    ("BARBELL_UPRIGHT_ROW", "SHOULDERS"),
    ("DUMBBELL_SHRUG", "SHOULDERS"),
    ("BARBELL_SHRUG", "SHOULDERS"),
    ("PUSH_PRESS", "SHOULDERS"),
    ("PUSH_JERK", "SHOULDERS"),
    ("CABLE_REAR_DELT_FLY", "SHOULDERS"),
    ("DUMBBELL_REAR_DELT_FLY", "SHOULDERS"),
    ("MACHINE_LATERAL_RAISE", "SHOULDERS"),
    ("MACHINE_REAR_DELT_FLY", "SHOULDERS"),
    # BICEPS
    ("BARBELL_CURL", "BICEPS"),
    ("DUMBBELL_CURL", "BICEPS"),
    ("HAMMER_CURL", "BICEPS"),
    ("INCLINE_DUMBBELL_CURL", "BICEPS"),
    ("CONCENTRATION_CURL", "BICEPS"),
    ("CABLE_CURL", "BICEPS"),
    ("EZ_BAR_CURL", "BICEPS"),
    ("PREACHER_CURL", "BICEPS"),
    ("MACHINE_PREACHER_CURL", "BICEPS"),
    ("SEATED_DUMBBELL_CURL", "BICEPS"),
    ("ZOTTMAN_CURL", "BICEPS"),
    ("REVERSE_CURL", "BICEPS"),
    ("CROSS_BODY_HAMMER_CURL", "BICEPS"),
    ("CABLE_HAMMER_CURL", "BICEPS"),
    # TRICEPS
    ("TRICEP_PUSHDOWN", "TRICEPS"),
    ("CABLE_TRICEP_PUSHDOWN", "TRICEPS"),
    ("ROPE_PUSHDOWN", "TRICEPS"),
    ("OVERHEAD_TRICEP_EXTENSION", "TRICEPS"),
    ("DUMBBELL_OVERHEAD_TRICEP_EXTENSION", "TRICEPS"),
    ("CABLE_OVERHEAD_TRICEP_EXTENSION", "TRICEPS"),
    ("SKULL_CRUSHER", "TRICEPS"),
    ("BENCH_DIP", "TRICEPS"),
    ("TRICEP_EXTENSION_MACHINE", "TRICEPS"),
    ("KICKBACK", "TRICEPS"),
    ("CLOSE_GRIP_BENCH_PRESS", "TRICEPS"),
    ("DIAMOND_PUSH_UP", "TRICEPS"),
    # LEGS
    ("SQUAT", "LEGS"),
    ("FRONT_SQUAT", "LEGS"),
    ("GOBLET_SQUAT", "LEGS"),
    ("DUMBBELL_SQUAT", "LEGS"),
    ("SUMO_SQUAT", "LEGS"),
    ("BULGARIAN_SPLIT_SQUAT", "LEGS"),
    ("DUMBBELL_LUNGE", "LEGS"),
    ("BARBELL_LUNGE", "LEGS"),
    ("WALKING_LUNGE", "LEGS"),
    ("REVERSE_DUMBBELL_LUNGE", "LEGS"),
    ("LEG_PRESS", "LEGS"),
    ("HACK_SQUAT", "LEGS"),
    ("SMITH_MACHINE_SQUAT", "LEGS"),
    ("BOX_SQUAT", "LEGS"),
    ("LEG_EXTENSION", "LEGS"),
    ("LEG_CURL", "LEGS"),
    ("SEATED_LEG_CURL", "LEGS"),
    ("LYING_LEG_CURL", "LEGS"),
    ("STANDING_LEG_CURL", "LEGS"),
    ("CALF_RAISE", "LEGS"),
    ("STANDING_CALF_RAISE", "LEGS"),
    ("SEATED_CALF_RAISE", "LEGS"),
    ("CABLE_KICKBACK", "LEGS"),
    ("BARBELL_HIP_THRUST", "LEGS"),
    ("DUMBBELL_HIP_THRUST", "LEGS"),
    ("GLUTE_BRIDGE", "LEGS"),
    ("STEP_UP", "LEGS"),
    ("CABLE_PULL_THROUGH", "LEGS"),
    ("KETTLEBELL_SWING", "LEGS"),
    ("SINGLE_LEG_PRESS", "LEGS"),
    ("SINGLE_LEG_EXTENSION", "LEGS"),
    ("SINGLE_LEG_CURL", "LEGS"),
    ("ROMANIAN_DEADLIFT", "LEGS"),
    ("LATERAL_LUNGE", "LEGS"),
    ("CURTSY_LUNGE", "LEGS"),
    ("PISTOL_SQUAT", "LEGS"),
    ("SISSY_SQUAT", "LEGS"),
    ("NORDIC_HAMSTRING_CURL", "LEGS"),
    ("ADDUCTOR_MACHINE", "LEGS"),
    ("ABDUCTOR_MACHINE", "LEGS"),
    # CORE
    ("PLANK", "CORE"),
    ("SIDE_PLANK", "CORE"),
    ("CRUNCH", "CORE"),
    ("SIT_UP", "CORE"),
    ("DECLINE_CRUNCH", "CORE"),
    ("BICYCLE_CRUNCH", "CORE"),
    ("RUSSIAN_TWIST", "CORE"),
    ("LEG_RAISE", "CORE"),
    ("HANGING_LEG_RAISE", "CORE"),
    ("HANGING_KNEE_RAISE", "CORE"),
    ("AB_WHEEL_ROLLOUT", "CORE"),
    ("CABLE_CRUNCH", "CORE"),
    ("CABLE_WOOD_CHOP", "CORE"),
    ("DEAD_BUG", "CORE"),
    ("HOLLOW_HOLD", "CORE"),
    ("V_UP", "CORE"),
    ("MOUNTAIN_CLIMBER", "CORE"),
    ("FLUTTER_KICK", "CORE"),
    ("PALLOF_PRESS", "CORE"),
    ("TOE_TOUCH", "CORE"),
    ("REVERSE_CRUNCH", "CORE"),
    ("WINDSHIELD_WIPER", "CORE"),
    ("DRAGON_FLAG", "CORE"),
    ("STABILITY_BALL_CRUNCH", "CORE"),
    ("STABILITY_BALL_ROLLOUT", "CORE"),
    # OLYMPIC
    ("POWER_CLEAN", "OLYMPIC"),
    ("HANG_POWER_CLEAN", "OLYMPIC"),
    ("CLEAN_AND_JERK", "OLYMPIC"),
    ("SNATCH", "OLYMPIC"),
    ("POWER_SNATCH", "OLYMPIC"),
    ("HANG_CLEAN", "OLYMPIC"),
    ("HANG_SNATCH", "OLYMPIC"),
    ("CLEAN_PULL", "OLYMPIC"),
    ("SNATCH_PULL", "OLYMPIC"),
    # CARDIO / CONDITIONING
    ("BURPEE", "CARDIO"),
    ("JUMPING_JACK", "CARDIO"),
    ("JUMP_ROPE", "CARDIO"),
    ("BATTLE_ROPES", "CARDIO"),
    ("SLED_PUSH", "CARDIO"),
    ("FARMERS_WALK", "CARDIO"),
    ("BEAR_CRAWL", "CARDIO"),
    ("SLED_PULL", "CARDIO"),
    # PLYOMETRICS
    ("BOX_JUMP", "PLYOMETRICS"),
    ("BOX_JUMP_STEP_DOWN", "PLYOMETRICS"),
    ("DEPTH_JUMP", "PLYOMETRICS"),
    ("BROAD_JUMP", "PLYOMETRICS"),
    ("LATERAL_BOUND", "PLYOMETRICS"),
    ("TUCK_JUMP", "PLYOMETRICS"),
    ("SPLIT_JUMP", "PLYOMETRICS"),
    # FLEXIBILITY
    ("FOAM_ROLL", "FLEXIBILITY"),
    ("STATIC_STRETCH", "FLEXIBILITY"),
]


def lookup(fitbod_name: str) -> tuple[str, str] | None:
    """Return (garmin_name, category) from Tier 1 map, or None."""
    return EXERCISE_MAP.get(fitbod_name)
